### PR TITLE
Example for using ERA5 data

### PR DESCRIPTION
**Pull request by syedhamidali**
Added notebook for ERA5, and it contains:
- `cdsapi` installation
- setup`.cdsapirc`
- initialization
- constraint
- visualization

### CODE REVIEW

**Comment by syedhamidali** [comment]
You can review the notebook [here](https://github.com/syedhamidali/PyDDA/blob/master/notebooks/ERA5_cdsapi.ipynb).

**Comment by Qxaqq** [comment]
The vertical speed  of downloaded ERA5 is Pa/s in the P coordinate system. May I ask whether the coordinate was converted to m/s in the Z coordinate system during the wind field initialization?

**Comment by Qxaqq** [comment]
> You can review the notebook [here](https://githubfast.com/syedhamidali/PyDDA/blob/master/notebooks/ERA5_cdsapi.ipynb).

The vertical speed of downloaded ERA5 is Pa/s in the P coordinate system. Is it converted to m/s in the Z coordinate system during wind field initialization?

**Comment by syedhamidali** [comment]
@Qxaqq I think we use geopotential to get the height in meters when interpolating the grid; I could be wrong, but possibly @rcjackson can help us out here.

**Pull request merged**
